In [9]:
import pandas as pd
import random

In [14]:
file = "../data/raw/User Master List.xlsx"
df = pd.read_excel(file, sheet_name="Data")
df.head()

,Portal ID,firstname,lastname,email,country,manager_portalid,grade,employee_type,Training Goal,hireddate,emp_country_name,emp_practise,L1,L2,L3,L4,L5,L6
0,24453,Maureen,Khadloya,24453_sa@nttdataser.com,IND,24687.0,12,Employee,16.0,1997-11-24,India,Application Services,3371938.0,24451.0,24467.0,24335.0,24620.0,24687.0
1,24430,Deepika Raghavendra,R,24430_sa@nttdataser.com,IND,24731.0,13,Employee,16.0,1998-03-02,India,Application Services,3371938.0,24430.0,24484.0,24548.0,24607.0,24731.0
2,24463,Shefali,Joisa,24463_sa@nttdataser.com,IND,24716.0,13,Employee,16.0,1998-05-04,India,Application Services,3371938.0,24463.0,24512.0,24524.0,24605.0,24716.0
3,24465,Aastha,Kemkar,24465_sa@nttdataser.com,IND,24747.0,13,Employee,16.0,1998-05-18,India,Application Services,3371938.0,24443.0,24514.0,24554.0,24633.0,24747.0
4,24277,Venkatasai Subra,Balkrishna Shedde,24277_sa@nttdataser.com,IND,24749.0,13,Employee,16.0,1998-07-06,India,Application Services,3371938.0,24279.0,24521.0,24562.0,24639.0,24749.0

In [15]:
df['Training Goal'] = df['Training Goal'] + random.randint(2, 5)
df.head()

,Portal ID,firstname,lastname,email,country,manager_portalid,grade,employee_type,Training Goal,hireddate,emp_country_name,emp_practise,L1,L2,L3,L4,L5,L6
0,24453,Maureen,Khadloya,24453_sa@nttdataser.com,IND,24687.0,12,Employee,18.0,1997-11-24,India,Application Services,3371938.0,24451.0,24467.0,24335.0,24620.0,24687.0
1,24430,Deepika Raghavendra,R,24430_sa@nttdataser.com,IND,24731.0,13,Employee,18.0,1998-03-02,India,Application Services,3371938.0,24430.0,24484.0,24548.0,24607.0,24731.0
2,24463,Shefali,Joisa,24463_sa@nttdataser.com,IND,24716.0,13,Employee,18.0,1998-05-04,India,Application Services,3371938.0,24463.0,24512.0,24524.0,24605.0,24716.0
3,24465,Aastha,Kemkar,24465_sa@nttdataser.com,IND,24747.0,13,Employee,18.0,1998-05-18,India,Application Services,3371938.0,24443.0,24514.0,24554.0,24633.0,24747.0
4,24277,Venkatasai Subra,Balkrishna Shedde,24277_sa@nttdataser.com,IND,24749.0,13,Employee,18.0,1998-07-06,India,Application Services,3371938.0,24279.0,24521.0,24562.0,24639.0,24749.0

In [16]:
df.to_excel(file, sheet_name="Data", index=False)